mysite/blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemap import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

mysite/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    body = models.TextField()
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created'])]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

mysite/blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    to = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    comments = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'cols': 30, 'rows': 5}),
                               required=False)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()

mysite/blog/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, TrigramSimilarity
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from taggit.models import Tag

from .forms import EmailPostForm, CommentForm, SearchForm
from .models import Post


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    template_name = 'blog/post/list.html'
    paginate_by = 2


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 5)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    return render(request,
                  'blog/post/list.html',
                  {'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             slug=slug,
                             status=Post.Status.PUBLISHED)
    # Comments
    comments = post.comments.filter(active=True)
    form = CommentForm()
    # Similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'form': form,
                   'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read{post.title} on {post_url}\n\n" \
                      f"{cd['name']}`s comments: {cd['comments']}"
            send_mail(subject=subject,
                      message=message,
                      from_email='stasyand330@gamil.com',
                      recipient_list=[cd['to']])
            sent = True

    else:
        form = EmailPostForm()

    return render(request,
                  'blog/post/share.html',
                  {'post': post,
                   'form': form,
                   'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None

    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'blog/post/comment.html',
                  {'post': post,
                   'comment': comment,
                   'form': form})


def post_search(request):
    if 'query' not in request.GET:
        return redirect('blog:post_list')

    form = SearchForm(data=request.GET)
    if form.is_valid():
        query = form.cleaned_data['query']
        search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
        search_query = SearchQuery(query)

        results = Post.published.annotate(similarity=TrigramSimilarity('title', query)
                                          ).filter(similarity__gt=0.1).order_by('-similarity')

        return render(request, 'blog/post/search_results.html',
                      {'query': query,
                       'results': results})

mysite/blog/templates/blog/base.html
{% load django_bootstrap5 %}
{% load blog_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<title>{% block title %}{% endblock title %}</title>

		{# Load CSS and JavaScript #}
		{% bootstrap_css %}
		{% bootstrap_javascript %}
		{# Display django.contrib.messages as Bootstrap alerts #}
		{% bootstrap_messages %}
		<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	</head>

	<body>
		{# NavBar #}
		<nav class="navbar bg-success">
			<div class="container-fluid">
				<a class="navbar-brand fw-bold" href="{% url 'blog:post_list' %}">My Blog</a>
				
				{% search_form %}
			</div>
		</nav>

		<div class="container-fluid">
			<div class="row">
				{# Content #}
				<div class="col-9 p-4 border-end">
					{% block content %}{% endblock content %}
				</div>
				{# Sidebar #}
				<div class="col-3 p-4">
					<div class="right-sidebar">
						<h2>Posts</h2>
						<hr />
						<p>There`re {% total_posts %} posts</p>
						{# RSS #}
						<p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>
						<hr>
						{# Latest Posts #}
						<h4>Latest Posts</h4>
						{% show_latest_posts %}
						<hr>
						{# Most Comments Posts #}
						{% get_most_commented_posts as most_commented_posts %}
						<h4>Most Commented Posts</h3>
							<ul>
								{% for post in most_commented_posts %}
									<li>
										<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
									</li>
								{% endfor %}
							</ul>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

mysite/blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}

{% block title %}Add a Comment{% endblock title %}

{% block content %}

	{% if comment %}
			<h2>Your comment has been added.</h2>
			<p><a href="{{ post.get_absolute_url }}">Back to the Post</a></p>
	{% else %}
		{% include 'blog/post/includes/comment_form.html' %}
	{% endif %}

{% endblock content %}

mysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
	{# Post #}
	<h1 class="text-center">{{ post.title }}</h1>

	<p class="text-muted">Published {{ post.publish }} by {{ post.author }}</p>

	{{ post.body|markdown|linebreaks }}
	<hr>
	{# Share #}
	<p><a href="{% url 'blog:post_share' post.id%}">Share this post</a></p>
	<hr>
	{# Similar Comments #}
	<h2>Similar posts</h2>
	{% for post in similar_posts %}
		<p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
	{% endfor %}
	<hr>
	{# Comments#}
	{% with comments.count as total_comments %}
	<p>{{ total_comments }} comment{{ total_comments|pluralize }}</p>
	{% endwith %}

	{% for comment in comments %}
		<div class="alert alert-primary" role="alert">
			<p class="text-muted">
				Comment {{ forloop.counter }} by {{ comment.name }} on {{ comment.created }}
			</p>
			{{ comment.body }}
		</div>

	{% empty %}
		<p>There are no comments.</p>
	{% endfor %}
	<hr>
	{# Add a Comment #}
	{% include 'blog\post\includes\comment_form.html' %}

{% endblock content %}

mysite/blog/templates/blog/post/includes/comment_form.html
{% load django_bootstrap5 %}

<div class=row>
	<div class="col-6">
		<h2>Add a new comment</h2>
		
		<form action="{% url 'blog:post_comment' post.id %}" method="post" novalidate>
			{% csrf_token %}
		
			{% bootstrap_form form %}
			{% bootstrap_button button_type="submit" content="Add comment" %}
		</form>
	</div>
</div>

mysite/blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
		<li>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</li>
	{% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}My blog{% endblock title %}

{% block content %}

	<h1 class="text-center">
		{% if tag %}Posts tagged by "{{ tag }}"
		{% else %}All Posts
		{% endif %}
	</h1>

	{% for post in posts %}
		<a href="{{ post.get_absolute_url }}">
			<h2>{{ post.title }}</h2>
		</a>
		<p class="fst-italic">Tags:
			{% for tag in post.tags.all %}
				<a href="{% url 'blog:post_list_by_tag' tag.slug %}">
					{{ tag }}{% if not forloop.last %},{% endif %}
				</a>
			{% endfor %}
		</p>
		<p class="text-muted">
			Published {{ post.publish }} by {{ post.author }}
		</p>

		{{ post.body|markdown|truncatewords_html:30 }}
		<hr>
	{% endfor %}

	{% include 'pagination.html' with page=posts %}

{% endblock content %}

mysite/blog/templates/blog/post/search_form.html
{% load django_bootstrap5 %}

<form class="d-flex" action="{% url 'blog:post_search' %}" role="search" method="get">
	{% bootstrap_field form.query wrapper_class="me-1" show_label=False placeholder="Search" %}
	{% bootstrap_button button_class="btn-warning" button_type="submit" content="Search" %}
</form>

mysite/blog/templates/blog/post/search_results.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Search Result{% endblock title %}

{% block content %}

	<h1>Post containing "{{ query }}"</h1>
		<h3>
			{% with results.count as total_results %}
				Found {{ total_results }} result{{ total_results|pluralize }} 
			{% endwith %}
		</h3>
		{% for post in results %}
			<h4>
				<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
			</h4>
			{{ post.body|markdown|truncatewords_html:12 }}
			<hr>
		{% empty %}
			<p>There are no results for your query.</p>
		{% endfor %}

{% endblock content %}

mysite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block title %}Share a Post{% endblock title %}

{% block content %}
	{% if sent %}
		{# Success #}
		<h1>E-mail successfully sent</h1>
		<p>{{ post.title }} was successfully sent to {{ form.cleaned_data.to }}</p>
	{% else %}
		{# Form #}
		<h2>Share {{ post.title }}</h2>
		<div class="row">
			<div class="col-md-6 col-sm-12">
				<form method="post">
					{% csrf_token %}
					
					{% bootstrap_form form %}
					{% bootstrap_button button_type="submit" content="Share the Post" %}
				</form>
			</div>
		</div>
	{% endif %}
{% endblock content %}

mysite/blog/templates/pagination.html
<nav aria-label="Page navigation">
	<ul class="pagination justify-content-center">
		{% if page.has_previous %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="Previous">
					<span aria-hidden="true">&laquo;</span>
				</a>
			</li>
		{% endif %}
		<li class="page-item active" aria-current="page">
      <a class="page-link" href="#">Page {{ page.number }} of {{ page.paginator.num_pages }}</a>
    </li>
		{% if page.has_next %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next">
					<span aria-hidden="true">&raquo;</span>
				</a>
			</li>
		{% endif %}
	</ul>
</nav>